// components/content/YouTubeEmbed.vue
<template>
  <div class="youtube-embed-wrapper">
    <div v-if="!loaded" class="relative bg-gray-800 aspect-video flex items-center justify-center cursor-pointer border rounded-lg overflow-hidden" @click="loadVideo">
      <div class="absolute inset-0">
        <img 
          :src="`https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`"
          :alt="`Play ${videoId}`"
          class="w-full h-full object-cover"
          @error="(e) => e.target.src = `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`"
        />
      </div>
      <div class="absolute inset-0 bg-black bg-opacity-40 flex items-center justify-center">
        <div class="w-16 h-16 bg-red-600 rounded-full flex items-center justify-center hover:bg-red-700 transition-all transform hover:scale-105">
          <svg class="w-8 h-8 text-white ml-1" fill="currentColor" viewBox="0 0 20 20">
            <path d="M6.3 2.841A1.5 1.5 0 004 4.11v11.78a1.5 1.5 0 002.3 1.269l9.344-5.89a1.5 1.5 0 000-2.538L6.3 2.84z"/>
          </svg>
        </div>
      </div>
    </div>
    
    <div v-if="loaded" class="aspect-video bg-black rounded-lg overflow-hidden">
      <iframe
        :src="`https://www.youtube.com/embed/${videoId}?autoplay=1&playsinline=1&rel=0&modestbranding=1`"
        class="w-full h-full"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen
      ></iframe>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
	videoId: string
}

defineProps<Props>()
const loaded = ref(false)

const loadVideo = () => {
	loaded.value = true
}
</script>

// components/mdx/youtube-embed.tsx
'use client'

import Image from 'next/image'
import { useCallback, useState } from 'react'

interface YouTubeEmbedProps {
	videoId: string
	title?: string
}

export function YouTubeEmbed({ videoId, title = 'YouTube video' }: YouTubeEmbedProps) {
	const [isLoaded, setIsLoaded] = useState(false)

	const handleLoad = useCallback(() => {
		setIsLoaded(true)
	}, [])

	const thumbnailUrl = `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`

	return (
		<div className="not-prose relative my-6 overflow-hidden rounded-xl border border-fd-border">
			<div className="relative aspect-video w-full">
				{isLoaded ? (
					<iframe
						src={`https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1&rel=0`}
						title={title}
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
						allowFullScreen
						className="absolute inset-0 h-full w-full"
					/>
				) : (
					<button
						type="button"
						onClick={handleLoad}
						className="group absolute inset-0 flex h-full w-full cursor-pointer items-center justify-center bg-dark-base"
						aria-label={`Play ${title}`}
					>
						<Image
							src={thumbnailUrl}
							alt={title}
							fill
							sizes="(max-width: 768px) 100vw, 768px"
							className="object-cover transition-opacity group-hover:opacity-80"
							loading="lazy"
							unoptimized
						/>
						<div className="relative z-10 flex h-16 w-16 items-center justify-center rounded-full bg-red-600 transition-opacity group-hover:opacity-80">
							<svg viewBox="0 0 24 24" fill="white" className="ml-1 h-7 w-7" aria-hidden="true">
								<path d="M8 5v14l11-7z" />
							</svg>
						</div>
					</button>
				)}
			</div>
		</div>
	)
}
