// components/blog/BlogCard.vue
<script setup lang="ts">
import type PropType from 'vue'
import type ParsedContent from '@nuxt/content'
import FormatDate from "~/components/common/FormatDate.vue";

defineProps({
  post: {
    type: Object as PropType<typeof ParsedContent>,
    required: true
  },
})
</script>

<template>
  <NuxtLink v-if="post && post.published && post._path" :href="post._path"
    class="flex flex-col h-full overflow-hidden rounded-xl transition-all duration-300 hover:transform hover:scale-[1.02] bg-white dark:bg-pickled-bluewood-700/50 border border-gray-200 dark:border-pickled-bluewood-600">
    <div class="relative aspect-[16/9] overflow-hidden">
      <img
        :src="post.image"
        :alt="post.title"
        class="object-cover w-full h-full transition-transform duration-300 group-hover:scale-105"
        loading="lazy"
      />
      <div class="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent"></div>
    </div>

    <div class="flex flex-col flex-grow p-6">
      <div class="flex-grow">
        <h2 class="mb-3 text-xl font-bold tracking-tight text-gray-900 dark:text-white">
          {{ post.title }}
        </h2>
        <p class="mb-4 text-sm text-gray-600 dark:text-gray-300 line-clamp-2">
          {{ post.description }}
        </p>
      </div>

      <div class="flex items-center justify-between pt-4 border-t border-gray-200 dark:border-pickled-bluewood-600">
        <div class="flex items-center space-x-3">
          <img
            :src="post.avatar"
            class="w-8 h-8 rounded-full ring-2 ring-white dark:ring-pickled-bluewood-600"
            :alt="post.author"
            loading="lazy"
          >
          <span class="text-sm font-medium text-gray-900 dark:text-white">
            {{ post.author }}
          </span>
        </div>
        <time
          :datetime="new Date(post.timestamp * 1000).toISOString()"
          class="text-sm text-gray-500 dark:text-gray-400"
        >
          <FormatDate :date="new Date(post.timestamp * 1000)"/>
        </time>
      </div>
    </div>
  </NuxtLink>
</template>

// components/blog/blog-card.tsx
import Image from 'next/image'
import Link from 'next/link'
import { FormatDate } from '@/components/common/format-date'

interface BlogCardProps {
	page: {
		url: string
		data: {
			title: string
			description?: string
			image?: string
			date: string | Date
			author: string
			avatar?: string
		}
	}
}

export function BlogCard({ page }: BlogCardProps) {
	const { url, data } = page

	return (
		<Link
			href={url}
			className="group flex flex-col overflow-hidden rounded-xl border border-fd-border bg-fd-card transition-colors duration-300 hover:bg-dark-control cursor-pointer"
		>
			<div className="relative aspect-[16/9] overflow-hidden">
				{data.image ? (
					<Image
						src={data.image}
						alt={data.title}
						fill
						sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
						className="object-cover"
						loading="lazy"
					/>
				) : (
					<div className="flex h-full items-center justify-center bg-dark-base">
						<span className="text-4xl font-bold text-accent/30">kftray</span>
					</div>
				)}
				<div className="absolute inset-0 bg-dark-base/20" />
			</div>

			<div className="flex flex-1 flex-col p-6">
				<div className="flex-1">
					<h2 className="mb-3 text-xl font-bold tracking-tight text-fd-foreground">{data.title}</h2>
					{data.description && (
						<p className="mb-4 line-clamp-2 text-sm text-fd-muted-foreground">{data.description}</p>
					)}
				</div>

				<div className="flex items-center justify-between border-t border-fd-border pt-4">
					<div className="flex items-center gap-3">
						{data.avatar && (
							<Image
								src={data.avatar}
								alt={data.author}
								width={32}
								height={32}
								className="rounded-full ring-2 ring-fd-background"
								loading="lazy"
							/>
						)}
						<span className="text-sm font-medium text-fd-foreground">{data.author}</span>
					</div>
					<time className="text-sm text-fd-muted-foreground">
						<FormatDate date={new Date(data.date)} />
					</time>
				</div>
			</div>
		</Link>
	)
}
